version: '3'
services:

  nodejs:
    build:
      context: ./javascript/
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./javascript:/app:cached

  python:
    build:
      context: ./python/
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    volumes:
      - ./python:/app:cached

  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    ports:
      - 8003:8003
    volumes:
      - ./php:/var/www/html:cached

  deno:
    build:
      context: ./typescript/
      dockerfile: Dockerfile
    ports:
      - 8004:8004
    volumes:
      - ./typescript:/app:cached
