version: '3'
services:

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    ports:
      - 8001:8001
    volumes:
      - ./javascript:/app:cached

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    ports:
      - 8002:8002
    volumes:
      - ./python:/app:cached

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - 8003:8003
    volumes:
      - ./php:/var/www/html:cached

  deno:
    build:
      context: .
      dockerfile: Dockerfile-deno
    ports:
      - 8004:8004
    volumes:
      - ./typescript:/app:cached
