version: '3'
services:

  nodejs:
    build:
      context: ./javascript/
      dockerfile: Dockerfile
    ports:
      - 8001:8001

  python:
    build:
      context: ./python/
      dockerfile: Dockerfile
    ports:
      - 8002:8002

  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    ports:
      - 8003:80

  deno:
    build:
      context: ./typescript/
      dockerfile: Dockerfile
    ports:
      - 8004:8004

  golang:
    build:
      context: ./golang/
      dockerfile: Dockerfile
    ports:
      - 8005:8005
